import { Topbar } from "@/components/shared";
import "../globals.css";


export const metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <main>
            <Topbar />
            <section className="w-full bg-green-300 s">
                {children}
            </section>
        </main>
    );
}
