import { EmailProvider } from "@/context/emailContext/EmailProvider";
import "../globals.css";


export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <EmailProvider>

    <main>{children}</main>
    </EmailProvider>
  );
}
