import "../globals.css";


export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>{children}</main>
  );
}
